In [1]:
import pandas as pd

train_df         = pd.read_csv("hf://datasets/openadmet/pxr-challenge-train-test/pxr-challenge_TRAIN.csv")
test_df          = pd.read_csv("hf://datasets/openadmet/pxr-challenge-train-test/pxr-challenge_TEST_BLINDED.csv")
train_counter_df = pd.read_csv("hf://datasets/openadmet/pxr-challenge-train-test/pxr-challenge_counter-assay_TRAIN.csv")
train_single_df  = pd.read_csv("hf://datasets/openadmet/pxr-challenge-train-test/pxr-challenge_single_concentration_TRAIN.csv")

In [2]:
train_df = pd.merge(train_df, train_counter_df, on="SMILES", how="outer", suffixes=("", "_counter"))
train_df = train_df[['SMILES', 'pEC50', 'pEC50_ci.lower (-log10(molarity))',  'pEC50_ci.upper (-log10(molarity))',  'Emax_estimate (log2FC vs. baseline)', 'Emax_ci.lower (log2FC vs. baseline)', 'Emax_ci.upper (log2FC vs. baseline)',        'pEC50_std.error (-log10(molarity))',   'Emax_std.error (log2FC vs. baseline)', 'pEC50_counter',       'pEC50_ci.lower (-log10(molarity))_counter',    'pEC50_ci.upper (-log10(molarity))_counter',       'Emax_estimate (log2FC vs. baseline)_counter',    'Emax_ci.lower (log2FC vs. baseline)_counter',       'Emax_ci.upper (log2FC vs. baseline)_counter',    'pEC50_std.error (-log10(molarity))_counter', 'Emax_std.error (log2FC vs. baseline)_counter']]
train_df.to_csv("train.csv", index=False)
train_df

,SMILES,pEC50,pEC50_ci.lower (-log10(molarity)),pEC50_ci.upper (-log10(molarity)),Emax_estimate (log2FC vs. baseline),Emax_ci.lower (log2FC vs. baseline),Emax_ci.upper (log2FC vs. baseline),pEC50_std.error (-log10(molarity)),Emax_std.error (log2FC vs. baseline),pEC50_counter,pEC50_ci.lower (-log10(molarity))_counter,pEC50_ci.upper (-log10(molarity))_counter,Emax_estimate (log2FC vs. baseline)_counter,Emax_ci.lower (log2FC vs. baseline)_counter,Emax_ci.upper (log2FC vs. baseline)_counter,pEC50_std.error (-log10(molarity))_counter,Emax_std.error (log2FC vs. baseline)_counter
0,BrC1=CC=C(C2(CNC(C3=CC=CN=C3)C3=NC=CN3)CCOCC2)...,4.51,4.098400,4.921600,2.81,2.296480,3.323520,0.2100,0.2620,4.43,4.03996,4.82004,1.59,1.22348,1.95652,0.199,0.187
1,BrC1=CC=CC2=C1CCC2NCC1=NOC2=C1COCC2,5.06,4.836560,5.283440,2.59,2.386160,2.793840,0.1140,0.1040,3.81,3.31412,4.30588,1.47,0.95256,1.98744,0.253,0.264
2,BrC1=CC=CC=C1C1CCCN1C1=NC=NC2=C1C=NN2,5.66,5.481836,5.838164,2.71,2.512040,2.907960,0.0909,0.1010,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000
3,C#CC(C)(C)N,2.01,0.763440,3.256560,2.16,1.438720,2.881280,0.6360,0.3680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,C#CC(C)(C)N1CCN(S(=O)(=O)N2CC3CCC2C3)CC1,4.93,4.634040,5.225960,2.44,2.146000,2.734000,0.1510,0.1500,3.04,2.68132,3.39868,1.63,1.21644,2.04356,0.183,0.211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4134,[H][C@@]12CCC[C@@]1(CNS(=O)(=O)C1=CC=CC3=CC=CN...,5.86,5.775132,5.944868,3.29,3.188080,3.391920,0.0433,0.0520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4135,[H][C@@]12CCC[C@@]1(CNS(=O)(=O)C1=CN(CC)N=C1)C...,4.80,4.711800,4.888200,2.60,2.467308,2.732692,0.0450,0.0677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4136,[H][C@]12CCCC(=O)N1C[C@@H]1C[C@H]2CN(C(=O)N2CC...,6.14,6.071204,6.208796,3.36,3.304140,3.415860,0.0351,0.0285,2.14,0.87188,3.40812,1.70,0.91012,2.48988,0.647,0.403
4137,[H][C@]12C[C@@H](OC(=O)C3=CC(OC)=C(OC)C(OC)=C3...,4.71,4.359160,5.060840,1.94,1.526440,2.353560,0.1790,0.2110,4.91,4.62972,5.19028,1.37,1.08972,1.65028,0.143,0.143
4138,[O-][N+]1=CC=CC=C1S,1.75,0.670040,2.829960,2.14,1.403040,2.876960,0.5510,0.3760,2.09,0.79640,3.38360,1.43,0.96940,1.89060,0.660,0.235

In [3]:
pretrain_df = train_single_df[~train_single_df["SMILES"].isin(train_df["SMILES"])]
pretrain_df = pretrain_df[['SMILES', 'concentration_M', 'log2_fc_estimate', 'log2_fc_stderr']]
pretrain_df.to_csv("pretrain.csv", index=False)
pretrain_df

,SMILES,concentration_M,log2_fc_estimate,log2_fc_stderr
0,CN1N=NN=C1C1=CC=CC(NC(=O)C2CNC(=O)C2)=C1,0.000008,-0.060085,0.113324
1,CC1=C(OC(F)(F)F)C=CC=C1C(=O)NC1=C2N=CC=CN2N=C1,0.000033,0.544938,0.114164
2,CC1=NOC(C2CCN(C(=O)CCN3NC(=O)C4=CC=CC=C4C3=O)C...,0.000033,-0.015018,0.114164
3,CC1=CSC(C(=O)NC2=CC=CN=C2N2CCOCC2)=C1Cl,0.000033,0.678915,0.127223
4,CC1=CC(Br)=CC=C1N1C=C(C2(O)CCCN(C(=O)CC3=CC=CN...,0.000033,0.637109,0.112362
...,...,...,...,...
20994,ClC1=CC=C2C(NCCCCN3CCOCC3)=CC=NC2=C1,0.000099,1.156694,0.220649
20995,CC1=CSC(C(=O)N2CCC3(CC2)CN(C(=O)CC2CCC2)C3)=C1Cl,0.000099,-0.207978,0.220649
20996,CC1=C(NC(=O)NC2CCN(C3CC3)CC2)C=NN1C1=CC=CC=C1,0.000099,0.199720,0.220649
21000,CC1=C(C2=NC(COC3=CC=CC(F)=C3)=NO2)N=NN1C1CCNCC1,0.000099,0.750014,0.220649
21002,O=C(N[C@H]1CC[C@@H](C(=O)N2CCCCC2)C1)C1CCCOC1,0.000099,1.404924,0.220649

In [4]:
test_df.to_csv("test.csv", index=False)